export const TOGGLE_MENU = 'TOGGLE_MENU';
export const CLOSE_MENU = 'CLOSE_MENU';

export const SHOW_PASSWD_MODAL = 'SHOW_PASSWD_MODAL';
export const HIDE_PASSWD_MODAL = 'HIDE_PASSWD_MODAL';

export const GOODS_LIST_REQUEST = 'GOODS_LIST_REQUEST';
export const GOODS_LIST_SUCCESS = 'GOODS_LIST_SUCCESS';
export const GOODS_LIST_FAIL = 'GOODS_LIST_FAIL';
export const GOODS_TEMP_LIST_REQUEST = 'GOODS_TEMP_LIST_REQUEST';
export const GOODS_CATE_SUCCESS = 'GOODS_CATE_SUCCESS';
export const GOODS_CHANGE_INFO = 'GOODS_CHANGE_INFO';
export const GOODS_EDIT_CATE_SUCCESS = 'GOODS_EDIT_CATE_SUCCESS';
export const GOODS_CATE_FETCH_SUCCESS = 'GOODS_CATE_FETCH_SUCCESS';
export const GOODS_CATE_SAVE_SUCCESS = 'GOODS_CATE_SAVE_SUCCESS';
export const GOODS_CATE_MODAL_OPEN = 'GOODS_CATE_MODAL_OPEN';
export const GOODS_CATE_MODAL_CANCEL = 'GOODS_CATE_MODAL_CANCEL';
export const GOODS_CATE_CAN_DELETE = 'GOODS_CATE_CAN_DELETE';
export const GOODS_CATE_CANT_DELETE = 'GOODS_CATE_CANT_DELETE';
export const GOODS_BASE_LIST_SUCCESS = 'GOODS_BASE_LIST_SUCCESS';

export const COMBOS_LIST_REQUEST = 'COMBOS_LIST_REQUEST';
export const COMBOS_LIST_SUCCESS = 'COMBOS_LIST_SUCCESS';
export const COMBOS_LIST_FAIL = 'COMBOS_LIST_FAIL';
export const COMBOS_CHANGE_INFO = 'COMBOS_CHANGE_INFO';

export const ROOM_TYPE_LIST_SUCCESS = 'ROOM_TYPE_LIST_SUCCESS';

export const TUAN_LIST_SUCCESS = 'TUAN_LIST_SUCCESS';
export const TUAN_VERIFY_LIST_SUCCESS = 'TUAN_VERIFY_LIST_SUCCESS';
export const TUAN_VERIFY_CODES = 'TUAN_VERIFY_CODES';

export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS';
export const ORDER_LIST_RESET = 'ORDER_LIST_RESET';
export const ORDER_TOTAL_LIST_SUCCESS = 'ORDER_TOTAL_LIST_SUCCESS';

export const SERVICE_LIST_SUCCESS = 'SERVICE_LIST_SUCCESS';
export const ORDER_DETAIL_SUCCESS = 'ORDER_DETAIL_SUCCESS';
export const ORDER_REFUND_SHOW = 'ORDER_REFUND_SHOW';
export const ORDER_REFUND_CLOSE = 'ORDER_REFUND_CLOSE';

export const SETTLEMENT_LIST_SUCCESS = 'SETTLEMENT_LIST_SUCCESS';


export const ACTIVITY_LIST_SUCCESS = 'ACTIVITY_LIST_SUCCESS';
export const ACTIVITY_INFO_FETCH_SUCCESS = 'ACTIVITY_INFO_FETCH_SUCCESS';

export const CHANNEL_INFO_FETCH_SUCCESS = 'CHANNEL_INFO_FETCH_SUCCESS';

export const COMMISSION_LIST_FETCH_SUCCESS = 'COMMISSION_LIST_FETCH_SUCCESS';
export const STOCK_FETCH_SUCCESS = 'STOCK_FETCH_SUCCESS';

export const EMPLOYEE_LIST_FETCH_SUCCESS = 'EMPLOYEE_LIST_FETCH_SUCCESS';
export const EMPLOYEE_ROLES_FETCH_SUCCESS = 'EMPLOYEE_ROLES_FETCH_SUCCESS';
export const EMPLOYEE_MSG_LIST = 'EMPLOYEE_MSG_LIST';

export const ROOM_LIST_FETCH_SUCCESS = 'ROOM_LIST_FETCH_SUCCESS';
export const ROOM_LIST_MODAL_CANCEL = 'ROOM_LIST_MODAL_CANCEL';
export const ROOM_LIST_MODAL_SHOW = 'ROOM_LIST_MODAL_SHOW';
export const ROOM_CATE_MODAL_CANCEL = 'ROOM_CATE_MODAL_CANCEL';
export const ROOM_CATE_MODAL_SHOW = 'ROOM_CATE_MODAL_SHOW';
export const ROOM_CATE_CAN_DELETE = 'ROOM_CATE_CAN_DELETE';
export const ROOM_CATE_CANT_DELETE = 'ROOM_CATE_CANT_DELETE';

export const BOOKING_VERIFY_LIST_SUCCESS = 'BOOKING_VERIFY_LIST_SUCCESS';
export const BOOKING_DATE_PERIOD_LIST = 'BOOKING_DATE_PERIOD_LIST';
export const BOOKING_DATE_PERIOD_COMBOS = 'BOOKING_DATE_PERIOD_COMBOS';
export const BOOKING_COMBO_EDIT_SHOW = 'BOOKING_COMBO_EDIT_SHOW';
export const BOOKING_COMBO_EDIT_CLOSE = 'BOOKING_COMBO_EDIT_CLOSE';
export const BOOKING_COMBO_ROOM_TYPE = 'BOOKING_COMBO_ROOM_TYPE';
export const BOOKING_COMBO_GOODS_COMBO = 'BOOKING_COMBO_GOODS_COMBO';
export const BOOKING_DATE_LIST = 'BOOKING_DATE_LIST';
export const BOOKING_PERIOD_LIST = 'BOOKING_PERIOD_LIST';
export const BOOKING_DAYS = 'BOOKING_DAYS';
export const BOOKING_ARRIVE_PERIOD_LIST = 'BOOKING_ARRIVE_PERIOD_LIST';
export const BOOKING_REFUND_ROOM_TYPE = 'BOOKING_REFUND_EDIT';

export const BOOKING_STOCK_BASE = 'BOOKING_STOCK_BASE';
export const BOOKING_STOCK = 'BOOKING_STOCK';
export const BOOKING_STOCK_EDIT_SHOW = 'BOOKING_STOCK_EDIT_SHOW';
export const BOOKING_STOCK_SET_NUMBER = 'BOOKING_STOCK_SET_NUMBER';
export const BOOKING_STOCK_EDIT_CLOSE = 'BOOKING_STOCK_EDIT_CLOSE';

export const BOOKING_STOCK_TPL_BASE = 'BOOKING_STOCK_TPL_BASE';
export const BOOKING_STOCK_TPL = 'BOOKING_STOCK_TPL';
export const BOOKING_STOCK_TPL_EDIT_SHOW = 'BOOKING_STOCK_TPL_EDIT_SHOW';
export const BOOKING_STOCK_TPL_SET_NUMBER = 'BOOKING_STOCK_TPL_SET_NUMBER';
export const BOOKING_STOCK_TPL_EDIT_CLOSE = 'BOOKING_STOCK_TPL_EDIT_CLOSE';

export const BOOKING_ROOM_TYPE = 'BOOKING_ROOM_TYPE';
export const BOOKING_COMBOS = 'BOOKING_COMBOS';
export const BOOKING_COMBOS_GOODS_LIST = 'BOOKING_COMBOS_GOODS_LIST';
export const BOOKING_COMBOS_INFO = 'BOOKING_COMBOS_INFO';
export const BOOKING_COMBOS_SET_NUMBER = 'BOOKING_COMBOS_SET_NUMBER';
export const BOOKING_COMBOS_ADD = 'BOOKING_COMBOS_ADD';
export const BOOKING_COMBOS_DELETE = 'BOOKING_COMBOS_DELETE';
export const BOOKING_ADD_QUERY = 'BOOKING_ADD_QUERY';
export const BOOKING_ADD_COMBO_ADD = 'BOOKING_ADD_COMBO_ADD';
export const BOOKING_ADD_COMBO_SET = 'BOOKING_ADD_COMBO_SET';
export const BOOKING_ADD_COMBO_DELETE = 'BOOKING_ADD_COMBO_DELETE';
export const BOOKING_ADD_COMBO_LIST = 'BOOKING_ADD_COMBO_LIST';
export const BOOKING_ADD_COMBO_QUERY = 'BOOKING_ADD_COMBO_QUERY';
export const BOOKING_ADD_COMBO_ERROR = 'BOOKING_ADD_COMBO_ERROR';
export const BOOKING_ADD_COMBO_ERROR_RESET = 'BOOKING_ADD_COMBO_ERROR_RESET';

export const FINANCE_ACCOUNT_LIST = 'FINANCE_ACCOUNT_LIST';
export const FINANCE_DRAW_LIST = 'FINANCE_DRAW_LIST';
export const FINANCE_DRAW_HISTORY = 'FINANCE_DRAW_HISTORY';

export const CHANNEL_TYPE_FETCH_SUCCESS = 'CHANNEL_TYPE_FETCH_SUCCESS';
export const CHANGE_TABS = 'CHANGE_TABS';

export const MEMBER_STATUS = 'MEMBER_STATUS';
export const MEMBER_RULES_INFO = 'MEMBER_RULES_INFO';
export const MEMBER_SET_RULES_LOG = 'MEMBER_SET_RULES_LOG';
export const MEMBER_SET_RULES_LOG_PAGE_INDEX = 'MEMBER_SET_RULES_LOG_PAGE_INDEX';
export const MEMBER_PRICE = 'MEMBER_PRICE';
export const MEMBER_LIST = 'MEMBER_LIST';
export const MEMBER_ORDER_LIST = 'MEMBER_ORDER_LIST';
export const MEMBER_OFFLINE_LIST = 'MEMBER_OFFLINE_LIST';
export const MEMBER_OTHER_INFO = 'MEMBER_OTHER_INFO';

export const TICKET_ACTIVITY = 'TICKET_ACTIVITY';
export const TICKET_ACTIVITY_LIST = 'TICKET_ACTIVITY_LIST';
export const TICKET_ACTIVITY_ACTIVE_LIST = 'TICKET_ACTIVITY_ACTIVE_LIST';
export const TICKET_ACTIVITY_CONFIG = 'TICKET_ACTIVITY_CONFIG';
export const TICKET_ACTIVITY_USAGE = 'TICKET_ACTIVITY_USAGE';

export const TICKET_LIST = 'TICKET_LIST';
export const TICKET_SUG_LIST = 'TICKET_SUG_LIST';
export const TICKET_VIEW = 'TICKET_VIEW';
export const TICKET_COPY = 'TICKET_COPY';

export const TICKET_VERIFY_LIST_SUCCESS = 'TICKET_VERIFY_LIST_SUCCESS';

export const QRCODE_LIST_FETCH_SUCCESS = 'QRCODE_LIST_FETCH_SUCCESS';

export const TUAN_DATE_LIST = 'TUAN_DATE_LIST';
export const TUAN_PERIOD_LIST = 'TUAN_PERIOD_LIST';

export const GROUPON_COMBO_LIST = 'GROUPON_COMBO_LIST';
export const GROUPON_COMBO = 'GROUPON_COMBO';

export const GROUPON = 'GROUPON';
export const FEEDBACK_LIST = 'FEEDBACK_LIST';

export const DRINKS_LIST_SUCCESS = 'DRINKS_LIST_SUCCESS';

export const SELL_COUNT_LIST_SUCCESS = 'SELL_COUNT_LIST_SUCCESS';
export const MESSAGELIST_FETCH_SUCCESS = 'MESSAGELIST_FETCH_SUCCESS';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const BRAND_MERCHANTLIST_FETCH_SUCCESS = 'BRAND_MERCHANTLIST_FETCH_SUCCESS';

export const WAITER_REWARD_LIST_SUCCESS = 'WAITER_REWARD_LIST_SUCCESS';
export const WAITER_REWARD_EMPLOYEE_LIST_SUCCESS = 'WAITER_REWARD_EMPLOYEE_LIST_SUCCESS';

export const WAITER_SET_LIST_SUCCESS = 'WAITER_SET_LIST_SUCCESS';
