export default {
    10: [false, 'appstore'],
    106: ['/goods', 'glyphicon-th-list'],
    107: ['/combos', 'glyphicon-sort-by-order'],
    116: ['/tuan', 'glyphicon-cog'],
    117: ['/verify', 'check'],
    130: ['/booking', 'glyphicon-lock'],
    14: ['/booking-verify', 'check-circle'],
    11: [false, 'hdd'],
    112: ['/order'],
    118: ['/total/order'],
    114: ['/activity', 'heart'],
    16: [false, 'pay-circle-o'],
    113: ['/settlement/list'],
    161: ['/settlement/withdraw'],
    12: [false, 'share-alt'],
    120: ['/channel', 'glyphicon-cog'],
    121: ['/commission', 'glyphicon-cog'],
    13: [false, 'setting'],
    109: ['/room'],
    108: ['/stock'],
    111: ['/employee'],
    131: ['/qrcode'],
    110: ['/meterial', 'download'],
    115: ['/service'],
    151: ['/telrecommendation'],
    152: ['/waiter-set'],
    17: [false, 'user'],
    170: ['/member/rules'],
    171: ['/member/list'],
    172: ['/member/offline'],
    18: [false, 'book'],
    180: ['/ticket-list'],
    181: ['/ticket-activity-list'],
    182: ['/ticket-activity-config'],
    183: ['/ticket-activity-usage'],
    184: ['/ticket-verify'],
    119: ['/feedback'],
    19: [false, 'file'],
    21: [false, 'database'],
    210: ['sell-count'],
    190: ['/drinks'],
    191: ['/waiter-reward-count']
};
